/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import clase.CafeteraDeAlbin;
import javax.swing.JOptionPane;

/**
 *
 * @author SP
 */
public class Ejercicio6 extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio6
     */
    public Ejercicio6() {
        initComponents(); 
         cmdIngresar.setEnabled(true);
        cmdLLenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
        cmdAgregar.setEnabled(false);
        cmdBorrar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtEstandar = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtLimite = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmdIngresar = new javax.swing.JButton();
        cmdAgregar = new javax.swing.JButton();
        cmdLLenar = new javax.swing.JButton();
        cmdServir = new javax.swing.JButton();
        cmdVaciar = new javax.swing.JButton();
        cmdBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Calisto MT", 2, 18)); // NOI18N
        jLabel1.setText("Ejercicio6");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 80, -1));

        jPanel2.setBackground(new java.awt.Color(0, 255, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jLabel4.setText("Capacidad Estandar");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 0, -1, -1));

        txtEstandar.setEditable(false);
        txtEstandar.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        txtEstandar.setForeground(new java.awt.Color(255, 255, 0));
        txtEstandar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstandar.setText("000000000");
        txtEstandar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstandarActionPerformed(evt);
            }
        });
        jPanel2.add(txtEstandar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 2, 14)); // NOI18N
        jLabel3.setText("Capacidad Limite");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 100, -1));

        txtLimite.setEditable(false);
        txtLimite.setFont(new java.awt.Font("Tempus Sans ITC", 3, 14)); // NOI18N
        txtLimite.setForeground(new java.awt.Color(153, 153, 255));
        txtLimite.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtLimite.setText("1000");
        jPanel2.add(txtLimite, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 110, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 160, 110));

        jLabel2.setFont(new java.awt.Font("Traditional Arabic", 2, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 51));
        jLabel2.setText("valores predeterminados");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 180, -1));

        jPanel3.setBackground(new java.awt.Color(153, 0, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 0, 102));
        jLabel5.setText("Galeria De Botones");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, -1, -1));

        cmdIngresar.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdIngresar.setForeground(new java.awt.Color(0, 153, 153));
        cmdIngresar.setText("Ingresar");
        cmdIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdIngresarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        cmdAgregar.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdAgregar.setForeground(new java.awt.Color(0, 102, 153));
        cmdAgregar.setText("Agregar");
        cmdAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdAgregarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        cmdLLenar.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdLLenar.setForeground(new java.awt.Color(255, 102, 102));
        cmdLLenar.setText("LLenar");
        cmdLLenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdLLenarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdLLenar, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 70, 100, -1));

        cmdServir.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdServir.setForeground(new java.awt.Color(255, 0, 0));
        cmdServir.setText("Servir");
        cmdServir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdServirActionPerformed(evt);
            }
        });
        jPanel3.add(cmdServir, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 70, 90, -1));

        cmdVaciar.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdVaciar.setForeground(new java.awt.Color(255, 255, 0));
        cmdVaciar.setText("Vaciar");
        cmdVaciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdVaciarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdVaciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 100, -1));

        cmdBorrar.setFont(new java.awt.Font("Trebuchet MS", 2, 18)); // NOI18N
        cmdBorrar.setText("Borrar");
        cmdBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdBorrarActionPerformed(evt);
            }
        });
        jPanel3.add(cmdBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 110, 90, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 230, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(360, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cmdIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdIngresarActionPerformed
         CafeteraDeAlbin albin;int estandar,limite; 
         JOptionPane.showMessageDialog(this,"Bienvenidos a la cafetera de albin disfrute de nuestro cafe de buena calidad");
        
        if (txtLimite.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese capacidad a desear", "error", JOptionPane.ERROR_MESSAGE);
            txtLimite.requestFocusInWindow();
        } else if (Integer.parseInt(txtLimite.getText().trim())==0){
            JOptionPane.showMessageDialog(this, "La capacidad limite de la cafetera no puede ser cero","error",JOptionPane.ERROR_MESSAGE);
            txtLimite.requestFocusInWindow();
            txtLimite.selectAll();
        }
        else if (txtEstandar.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese capacidad a desear", "error", JOptionPane.ERROR_MESSAGE);
            txtEstandar.requestFocusInWindow();
        } else{
            limite=Integer.parseInt(txtLimite.getText());
            estandar=Integer.parseInt(txtEstandar.getText());
            if (estandar >limite) {
                JOptionPane.showMessageDialog(this, "La capacidad estandar no puede sobrepasar el limite", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                albin= new CafeteraDeAlbin(estandar,limite);
                JOptionPane.showMessageDialog(this, "Valores Ingresados en la cafetera de albin");
                cmdIngresar.setEnabled(false);
                txtEstandar.setEditable(false);
                txtLimite.setEditable(false);
                cmdAgregar.setEnabled(true);
                cmdBorrar.setEnabled(true);
                cmdLLenar.setEnabled(true);
                cmdServir.setEnabled(true);
                cmdVaciar.setEnabled(true);
            }  
        }
    }//GEN-LAST:event_cmdIngresarActionPerformed

    private void cmdAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdAgregarActionPerformed
    int sw = 1;int estandar2,estandar,limite;
       
       limite=Integer.parseInt(txtLimite.getText());
       estandar=Integer.parseInt(txtEstandar.getText());
        CafeteraDeAlbin albin,mafe; 
        JOptionPane.showMessageDialog(this,"Bienvenidos a la cafetera de albin disfrute de nuestro cafe de buena calidad");
        do {
            try {
                int cafe=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese cantidad de cafe"));
                albin=new CafeteraDeAlbin(estandar,limite);
                mafe=albin.agregarcafe(cafe);
                estandar2=mafe.getCapacidadestandar();
                txtEstandar.setText(String.valueOf(estandar));
                JOptionPane.showMessageDialog(this, "cafe agregado satisfactoriamente");
                sw = 1;
            }catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ingrese un numero valido que la cafetera pueda registrar","Error",JOptionPane.ERROR_MESSAGE);
                sw=0;}
            catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }
        } while (sw == 0);
    }//GEN-LAST:event_cmdAgregarActionPerformed

    private void cmdLLenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdLLenarActionPerformed
      CafeteraDeAlbin albin;String llenado;int estandar,limite;
      JOptionPane.showMessageDialog(this,"Bienvenidos a la cafetera de albin disfrute de nuestro cafe de buena calidad");
       estandar=Integer.parseInt(txtEstandar.getText());
       limite=Integer.parseInt(txtLimite.getText()); 
       albin=new CafeteraDeAlbin(); 
       llenado=albin.llenarcafetera(); 
       JOptionPane.showMessageDialog(this, llenado);
        txtEstandar.setText(txtLimite.getText());
       

      
    }//GEN-LAST:event_cmdLLenarActionPerformed

    private void cmdServirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdServirActionPerformed
        int sw = 1;int estandar2,estandar,limite;
        JOptionPane.showMessageDialog(this,"Bienvenidos a la cafetera de albin disfrute de nuestro cafe de buena calidad");
        limite=Integer.parseInt(txtLimite.getText());
        estandar=Integer.parseInt(txtEstandar.getText());
        CafeteraDeAlbin albin,mafe;
        do {
            try {
                int taza=Integer.parseInt(JOptionPane.showInputDialog(this,"Ingrese cantidad a servir"));
                albin=new CafeteraDeAlbin(limite, estandar);
                mafe=albin.servircafe(taza);
                if (Double.parseDouble(txtEstandar.getText()) == 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad estandar es cero");
                } else if (mafe.getCapacidadestandar()== 0) {
                    JOptionPane.showMessageDialog(this, "La cantidad indicada es mayor a la cantidad estandar o es igual a la cantidad estandar, se llenará\n"
                        + "con lo que quede");
                    estandar2=mafe.getCapacidadestandar();
                    txtEstandar.setText(String.valueOf(estandar));
                } else {
                    estandar=mafe.getCapacidadestandar();
                    txtEstandar.setText(String.valueOf(estandar));
                    JOptionPane.showMessageDialog(this, "taza llenada satisfactoriamente");

                }
                sw = 1;
            } catch (NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Ingrese un numero valido que la cafetera pueda registrar","Error",JOptionPane.ERROR_MESSAGE);
                sw=0;
            }
            catch (NullPointerException e) {
                int res = JOptionPane.showConfirmDialog(this, "¿Seguro que deseas salir?", "Salir", JOptionPane.YES_NO_OPTION);
                if (res == 0) {
                    sw = 1;
                } else {
                    sw = 0;
                }
            }   
        } while (sw == 0);
    }//GEN-LAST:event_cmdServirActionPerformed

    private void cmdVaciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdVaciarActionPerformed
     CafeteraDeAlbin albin,mafe;int estandar2 = 0; 
     JOptionPane.showMessageDialog(this,"Bienvenidos a la cafetera de albin disfrute de nuestro cafe de buena calidad");
     albin=new CafeteraDeAlbin(); 
     mafe=albin.vaciarcafetera(); 
      txtEstandar.setText(String.valueOf(estandar2));
        JOptionPane.showMessageDialog(this, "Cafetera vaciada"); 
        JOptionPane.showMessageDialog(this,"Gracias por disfrutar de los servicios y productos de la cafetera de albin !Vuelvan Pronto y Con Mas Propina!");
    }//GEN-LAST:event_cmdVaciarActionPerformed

    private void cmdBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdBorrarActionPerformed
       cmdIngresar.setEnabled(true);
        cmdLLenar.setEnabled(false);
        cmdServir.setEnabled(false);
        cmdVaciar.setEnabled(false);
        cmdBorrar.setEnabled(true);
        cmdAgregar.setEnabled(false); 
        txtEstandar.setText("000000000");
        txtLimite.setText("1000");
        txtLimite.selectAll();
        txtLimite.requestFocusInWindow(); 
        
        
    }//GEN-LAST:event_cmdBorrarActionPerformed

    private void txtEstandarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstandarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEstandarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio6.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio6().setVisible(true);
            } 
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdAgregar;
    private javax.swing.JButton cmdBorrar;
    private javax.swing.JButton cmdIngresar;
    private javax.swing.JButton cmdLLenar;
    private javax.swing.JButton cmdServir;
    private javax.swing.JButton cmdVaciar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtEstandar;
    private javax.swing.JTextField txtLimite;
    // End of variables declaration//GEN-END:variables
}
